-- First, add missing columns to the cars table
ALTER TABLE public.cars 
ADD COLUMN IF NOT EXISTS description TEXT,
ADD COLUMN IF NOT EXISTS features TEXT,
ADD COLUMN IF NOT EXISTS images TEXT[],
ADD COLUMN IF NOT EXISTS agency TEXT,
ADD COLUMN IF NOT EXISTS island TEXT,
ADD COLUMN IF NOT EXISTS category TEXT,
ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'available',
ADD COLUMN IF NOT EXISTS type TEXT DEFAULT 'Car';

-- Insert car data for Aggelos Rentals fleet
-- Note: Using license_plate as the unique identifier (id field from JSON)
INSERT INTO public.cars (
  license_plate,
  make,
  model,
  year,
  daily_rate,
  transmission,
  fuel_type,
  seats,
  description,
  features,
  images,
  agency,
  island,
  category,
  status,
  type,
  is_available
) VALUES
  ('ΖΤΖ4206', 'Fiat', 'Panda Hybrid', 2024, 420, 'Manual', 'Hybrid', 5, 'Υβριδικό μοντέλο με χαμηλή κατανάλωση και υψηλή απόδοση.', 'Κλιματισμός, Bluetooth, USB, ABS, 5 Θέσεις, Υβριδική τεχνολογία, ECO λειτουργία, Compact μέγεθος, Χαμηλή κατανάλωση', ARRAY['/lovable-uploads/fleet/fiat-panda-hybrid.jpg'], 'aggelos-rentals', 'Piraeus', 'Compact', 'rented', 'Car', false),
  ('ΖΤΖ4232', 'Fiat', 'Panda Hybrid', 2024, 420, 'Manual', 'Hybrid', 5, 'Υβριδικό μοντέλο με χαμηλή κατανάλωση και υψηλή απόδοση.', 'Κλιματισμός, Bluetooth, USB, ABS, 5 Θέσεις, Υβριδική τεχνολογία, ECO λειτουργία, Compact μέγεθος, Χαμηλή κατανάλωση', ARRAY['/lovable-uploads/fleet/fiat-panda-hybrid.jpg'], 'aggelos-rentals', 'Piraeus', 'Compact', 'available', 'Car', true),
  ('ΖΤΖ4208', 'Fiat', 'Panda Hybrid', 2024, 420, 'Manual', 'Hybrid', 5, 'Υβριδικό μοντέλο με χαμηλή κατανάλωση και υψηλή απόδοση.', 'Κλιματισμός, Bluetooth, USB, ABS, 5 Θέσεις, Υβριδική τεχνολογία, ECO λειτουργία, Compact μέγεθος, Χαμηλή κατανάλωση', ARRAY['/lovable-uploads/fleet/fiat-panda-hybrid.jpg'], 'aggelos-rentals', 'Piraeus', 'Compact', 'available', 'Car', true),
  ('ΖΝΙ7735', 'Fiat', 'Panda Hybrid', 2024, 420, 'Manual', 'Hybrid', 5, 'Υβριδικό μοντέλο με χαμηλή κατανάλωση και υψηλή απόδοση.', 'Κλιματισμός, Bluetooth, USB, ABS, 5 Θέσεις, Υβριδική τεχνολογία, ECO λειτουργία, Compact μέγεθος, Χαμηλή κατανάλωση', ARRAY['/lovable-uploads/fleet/fiat-panda-hybrid.jpg'], 'aggelos-rentals', 'Piraeus', 'Compact', 'available', 'Car', true),
  ('XPI1202', 'Mitsubishi', 'Spacestar', 2025, 420, 'Manual', 'Petrol', 5, 'Ευέλικτο και οικονομικό, ιδανικό για κίνηση στην πόλη.', 'Κλιματισμός, Bluetooth, USB, ABS, 5 Θέσεις', ARRAY['/lovable-uploads/fleet/mitsubishi-spacestar.jpg'], 'aggelos-rentals', 'Piraeus', 'Compact', 'available', 'Car', true),
  ('XPI1203', 'Mitsubishi', 'Spacestar', 2025, 420, 'Manual', 'Petrol', 5, 'Ευέλικτο και οικονομικό, ιδανικό για κίνηση στην πόλη.', 'Κλιματισμός, Bluetooth, USB, ABS, 5 Θέσεις', ARRAY['/lovable-uploads/fleet/mitsubishi-spacestar.jpg'], 'aggelos-rentals', 'Piraeus', 'Compact', 'available', 'Car', true),
  ('XEH1056', 'Fiat', 'Panda', 2022, 380, 'Manual', 'Petrol', 5, 'Ευέλικτο και οικονομικό, ιδανικό για κίνηση στην πόλη.', 'Κλιματισμός, Bluetooth, USB, ABS, 5 Θέσεις, ECO λειτουργία, Compact μέγεθος, Χαμηλή κατανάλωση', ARRAY['/lovable-uploads/fleet/fiat-panda.jpg'], 'aggelos-rentals', 'Piraeus', 'Compact', 'rented', 'Car', false),
  ('ΧΕΗ1080', 'Fiat', 'Panda', 2022, 380, 'Manual', 'Petrol', 5, 'Ευέλικτο και οικονομικό, ιδανικό για κίνηση στην πόλη.', 'Κλιματισμός, Bluetooth, USB, ABS, 5 Θέσεις, ECO λειτουργία, Compact μέγεθος, Χαμηλή κατανάλωση', ARRAY['/lovable-uploads/fleet/fiat-panda.jpg'], 'aggelos-rentals', 'Piraeus', 'Compact', 'rented', 'Car', false),
  ('ΧΕΗ1172', 'Fiat', 'Panda', 2022, 380, 'Manual', 'Petrol', 5, 'Ευέλικτο και οικονομικό, ιδανικό για κίνηση στην πόλη.', 'Κλιματισμός, Bluetooth, USB, ABS, 5 Θέσεις, ECO λειτουργία, Compact μέγεθος, Χαμηλή κατανάλωση', ARRAY['/lovable-uploads/fleet/fiat-panda.jpg'], 'aggelos-rentals', 'Piraeus', 'Compact', 'rented', 'Car', false),
  ('ΙΡΙ4941', 'Fiat', 'Panda', 2019, 350, 'Manual', 'Petrol', 5, 'Ευέλικτο και οικονομικό, ιδανικό για κίνηση στην πόλη.', 'Κλιματισμός, Bluetooth, USB, ABS, 5 Θέσεις, ECO λειτουργία, Compact μέγεθος, Χαμηλή κατανάλωση', ARRAY['/lovable-uploads/fleet/fiat-panda.jpg'], 'aggelos-rentals', 'Piraeus', 'Compact', 'rented', 'Car', false),
  ('BKA9814', 'Suzuki', 'Celerio', 2021, 350, 'Manual', 'Petrol', 5, 'Ευέλικτο και οικονομικό, ιδανικό για κίνηση στην πόλη.', 'Κλιματισμός, Bluetooth, USB, ABS, 5 Θέσεις, Μικρές διαστάσεις, Εύκολο παρκάρισμα', ARRAY['/lovable-uploads/fleet/suzuki-celerio.jpg'], 'aggelos-rentals', 'Piraeus', 'Compact', 'available', 'Car', true),
  ('ΒΚΑ9639', 'Suzuki', 'Celerio', 2021, 350, 'Manual', 'Petrol', 5, 'Ευέλικτο και οικονομικό, ιδανικό για κίνηση στην πόλη.', 'Κλιματισμός, Bluetooth, USB, ABS, 5 Θέσεις, Μικρές διαστάσεις, Εύκολο παρκάρισμα', ARRAY['/lovable-uploads/fleet/suzuki-celerio.jpg'], 'aggelos-rentals', 'Piraeus', 'Compact', 'available', 'Car', true),
  ('YTK6488', 'Fiat', 'Panda', 2021, 380, 'Manual', 'Petrol', 5, 'Ευέλικτο και οικονομικό, ιδανικό για κίνηση στην πόλη.', 'Κλιματισμός, Bluetooth, USB, ABS, 5 Θέσεις, ECO λειτουργία, Compact μέγεθος, Χαμηλή κατανάλωση', ARRAY['/lovable-uploads/fleet/fiat-panda.jpg'], 'aggelos-rentals', 'Piraeus', 'Compact', 'available', 'Car', true),
  ('ITB8392', 'Citroen', 'C1', 2020, 350, 'Manual', 'Petrol', 5, 'Άνετο και ασφαλές, ιδανικό για οικογενειακές διαδρομές.', 'Κλιματισμός, Bluetooth, USB, ABS, 5 Θέσεις, Apple CarPlay, Σύστημα υποβοήθησης λωρίδας', ARRAY['/lovable-uploads/fleet/citroen-c1.jpg'], 'aggelos-rentals', 'Piraeus', 'Medium', 'available', 'Car', true),
  ('EMN7458', 'Toyota', 'Aygo', 2018, 350, 'Manual', 'Petrol', 5, 'Ευέλικτο και οικονομικό, ιδανικό για κίνηση στην πόλη.', 'Κλιματισμός, Bluetooth, USB, ABS, 5 Θέσεις, Μικρές διαστάσεις, Εύκολο παρκάρισμα', ARRAY['/lovable-uploads/fleet/toyota-aygo.jpg'], 'aggelos-rentals', 'Piraeus', 'Compact', 'available', 'Car', true),
  ('ΒΜΖ1133', 'Citroen', 'C3', 2025, 650, 'Manual', 'Petrol', 5, 'Άνετο και ασφαλές, ιδανικό για οικογενειακές διαδρομές.', 'Κλιματισμός, Bluetooth, USB, ABS, 5 Θέσεις, Αυτόματο κιβώτιο, Apple CarPlay, Σύστημα υποβοήθησης λωρίδας', ARRAY['/lovable-uploads/fleet/citroen-c3.jpg'], 'aggelos-rentals', 'Piraeus', 'Medium', 'rented', 'Car', false),
  ('ΒΜΖ1140', 'Citroen', 'C3', 2025, 650, 'Manual', 'Petrol', 5, 'Άνετο και ασφαλές, ιδανικό για οικογενειακές διαδρομές.', 'Κλιματισμός, Bluetooth, USB, ABS, 5 Θέσεις, Αυτόματο κιβώτιο, Apple CarPlay, Σύστημα υποβοήθησης λωρίδας', ARRAY['/lovable-uploads/fleet/citroen-c3.jpg'], 'aggelos-rentals', 'Piraeus', 'Medium', 'available', 'Car', true),
  ('ΕΜΤ5763', 'Peugeot', '208', 2020, 420, 'Manual', 'Petrol', 5, 'Άνετο και ασφαλές, ιδανικό για οικογενειακές διαδρομές.', 'Κλιματισμός, Bluetooth, USB, ABS, 5 Θέσεις, Οθόνη αφής, Apple CarPlay, Ενεργό Cruise Control', ARRAY['/lovable-uploads/fleet/peugeot-208.jpg'], 'aggelos-rentals', 'Piraeus', 'Medium', 'rented', 'Car', false),
  ('ΧΗΖ6448', 'Peugeot', '208', 2024, 520, 'Manual', 'Petrol', 5, 'Άνετο και ασφαλές, ιδανικό για οικογενειακές διαδρομές.', 'Κλιματισμός, Bluetooth, USB, ABS, 5 Θέσεις, Οθόνη αφής, Apple CarPlay, Ενεργό Cruise Control', ARRAY['/lovable-uploads/fleet/peugeot-208.jpg'], 'aggelos-rentals', 'Piraeus', 'Medium', 'rented', 'Car', false),
  ('ΧΗΖ5114', 'Peugeot', '208', 2024, 520, 'Manual', 'Petrol', 5, 'Άνετο και ασφαλές, ιδανικό για οικογενειακές διαδρομές.', 'Κλιματισμός, Bluetooth, USB, ABS, 5 Θέσεις, Οθόνη αφής, Apple CarPlay, Ενεργό Cruise Control', ARRAY['/lovable-uploads/fleet/peugeot-208.jpg'], 'aggelos-rentals', 'Piraeus', 'Medium', 'available', 'Car', true),
  ('ΙΥΥ5733', 'Kia', 'Picanto', 2021, 450, 'Automatic', 'Petrol', 5, 'Ευέλικτο και οικονομικό, ιδανικό για κίνηση στην πόλη.', 'Κλιματισμός, Bluetooth, USB, ABS, 5 Θέσεις, Αυτόματο κιβώτιο, Μικρές διαστάσεις, Εύκολο παρκάρισμα', ARRAY['/lovable-uploads/fleet/kia-picanto.jpg'], 'aggelos-rentals', 'Piraeus', 'Compact', 'rented', 'Car', false),
  ('XHO5992', 'Mitsubishi', 'Spacestar', 2025, 520, 'Automatic', 'Petrol', 5, 'Ευέλικτο και οικονομικό, ιδανικό για κίνηση στην πόλη.', 'Κλιματισμός, Bluetooth, USB, ABS, 5 Θέσεις', ARRAY['/lovable-uploads/fleet/mitsubishi-spacestar.jpg'], 'aggelos-rentals', 'Piraeus', 'Compact', 'available', 'Car', true),
  ('XHO5993', 'Mitsubishi', 'Spacestar', 2025, 520, 'Automatic', 'Petrol', 5, 'Ευέλικτο και οικονομικό, ιδανικό για κίνηση στην πόλη.', 'Κλιματισμός, Bluetooth, USB, ABS, 5 Θέσεις', ARRAY['/lovable-uploads/fleet/mitsubishi-spacestar.jpg'], 'aggelos-rentals', 'Piraeus', 'Compact', 'available', 'Car', true),
  ('XHE7736', 'MG', 'ZS', 2024, 720, 'Automatic', 'Petrol', 5, 'Ισχυρό και ευρύχωρο SUV, ιδανικό για κάθε προορισμό.', 'Κλιματισμός, Bluetooth, USB, ABS, 5 Θέσεις, Αυτόματο κιβώτιο, Μεγάλος χώρος αποσκευών, Cruise Control, SUV επιδόσεις, Οθόνη αφής, Σύστημα πλοήγησης', ARRAY['/lovable-uploads/fleet/mg-zs.jpg'], 'aggelos-rentals', 'Piraeus', 'SUV', 'available', 'Car', true),
  ('ZTB5942', 'Citroen', 'C3', 2022, 600, 'Automatic', 'Petrol', 5, 'Άνετο και ασφαλές, ιδανικό για οικογενειακές διαδρομές.', 'Κλιματισμός, Bluetooth, USB, ABS, 5 Θέσεις, Αυτόματο κιβώτιο, Apple CarPlay, Σύστημα υποβοήθησης λωρίδας', ARRAY['/lovable-uploads/fleet/citroen-c3.jpg'], 'aggelos-rentals', 'Piraeus', 'Medium', 'available', 'Car', true),
  ('XPN1315', 'MG', '3 Hybrid', 2025, 720, 'Automatic', 'Hybrid', 5, 'Υβριδικό μοντέλο με χαμηλή κατανάλωση και υψηλή απόδοση.', 'Κλιματισμός, Bluetooth, USB, ABS, 5 Θέσεις, Υβριδική τεχνολογία, ECO λειτουργία, Αυτόματο κιβώτιο, Σύστημα πλοήγησης', ARRAY['/lovable-uploads/fleet/mg-3-hybrid.jpg'], 'aggelos-rentals', 'Piraeus', 'Compact', 'available', 'Car', true),
  ('ΕΡΙ4728', 'Jeep', 'Renegade UPLAND Edition 4xe', 2023, 1200, 'Automatic', 'Petrol', 5, 'Ισχυρό και ευρύχωρο SUV, ιδανικό για κάθε προορισμό.', 'Κλιματισμός, Bluetooth, USB, ABS, 5 Θέσεις, Αυτόματο κιβώτιο, Μεγάλος χώρος αποσκευών, Cruise Control, 4x4, Οθόνη αφής', ARRAY['/lovable-uploads/fleet/jeep-renegade-upland-edition-4xe.jpg'], 'aggelos-rentals', 'Piraeus', 'SUV', 'available', 'Car', true),
  ('ΝΚΝ9580', 'Mercedes Benz', 'GLB', 2023, 1400, 'Automatic', 'Petrol', 7, 'Ισχυρό και ευρύχωρο SUV, ιδανικό για κάθε προορισμό.', 'Κλιματισμός, Bluetooth, USB, ABS, 5 Θέσεις, Αυτόματο κιβώτιο, Μεγάλος χώρος αποσκευών, Cruise Control, Πολυτελές εσωτερικό, Οθόνη αφής', ARRAY['/lovable-uploads/fleet/mercedes-benz-glb.jpg'], 'aggelos-rentals', 'Piraeus', 'SUV', 'available', 'Car', true)
ON CONFLICT (license_plate) DO UPDATE SET
  make = EXCLUDED.make,
  model = EXCLUDED.model,
  year = EXCLUDED.year,
  daily_rate = EXCLUDED.daily_rate,
  transmission = EXCLUDED.transmission,
  fuel_type = EXCLUDED.fuel_type,
  seats = EXCLUDED.seats,
  description = EXCLUDED.description,
  features = EXCLUDED.features,
  images = EXCLUDED.images,
  agency = EXCLUDED.agency,
  island = EXCLUDED.island,
  category = EXCLUDED.category,
  status = EXCLUDED.status,
  type = EXCLUDED.type,
  is_available = EXCLUDED.is_available,
  updated_at = NOW();
